# Azul CRaC Spring Boot

# Stage 1: Build the application
FROM maven:3.9-eclipse-temurin-25-alpine AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn package -DskipTests -q

# Stage 2: Create the CRaC checkpoint
FROM azul/zulu-openjdk:25-jdk-crac-latest AS checkpoint
WORKDIR /app.
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://springlean-pg:5432/springlean
COPY --from=builder /app/target/*.jar app.jar
RUN java -Dspring.context.checkpoint=onRefresh -XX:CRaCCheckpointTo=/checkpoint -XX:CRaCEngine=warp -jar app.jar || true

# Stage 3: Runtime with CRaC restoreRE
FROM azul/zulu-openjdk:25-jdk-crac-latest
RUN addgroup -S app && adduser -S app -G app
WORKDIR /app
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://springlean-pg:5432/springlean
COPY --from=checkpoint /checkpoint /checkpoint
COPY --from=builder /app/target/*.jar app.jar
RUN chown -R app:app /app /checkpoint
USER app
EXPOSE 8080
ENTRYPOINT ["java","-XX:CRaCRestoreFrom=/checkpoint","-XX:CRaCEngine=warp"]
