# Server
server.port=8080

# Virtual Threads
spring.threads.virtual.enabled=true

# Log
spring.jmx.enabled=false
spring.main.banner-mode=off
spring.main.log-startup-info=true

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/springlean
spring.datasource.username=springlean
spring.datasource.password=springlean
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=2000

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
management.endpoint.health.probes.enabled=true

spring.sql.init.mode=never

logging.level.root=INFO
logging.level.dev.hogwai=WARN
logging.pattern.console=%m%n
